title: OR-URISA Young Professionals
production_url: http://orurisayp.org
repository: OR-URISA-YPs/or-urisa-yps.github.com

author:
  name: The Oregon URISA Young Professionals Group
  email: or-urisa-young-professionals@googlegroups.com
  github: OR-URISA-YPs
  twitter: ORURISAYP

permalink: /posts/:year/:month/:day/:title

highlighter: rouge
timezone: America/Los_Angeles
encoding: utf-8

analytics:
  google:
    tracking_id: "UA-40320276-1"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

gems:
  - jekyll-redirect-from
